const crypto=require('node:crypto');
const INJECTION_PATTERNS=[[/ignore (all|any|the)? ?previous instructions?/i,'instruction_override'],[/system prompt/i,'system_prompt_request'],[/reveal|exfiltrate|dump .*(secret|token|password|memory)/i,'data_exfiltration'],[/<\/?(?:system|assistant|tool)>/i,'role_markup'],[/do not tell (the )?user/i,'concealment']];
function injectionFlags(text){return INJECTION_PATTERNS.filter(([pattern])=>pattern.test(String(text||''))).map(([,code])=>code);}
function encryptionKey(){const raw=process.env.MEMORY_ENCRYPTION_KEY_BASE64||'';const key=Buffer.from(raw,'base64');if(key.length!==32)throw new Error('MEMORY_ENCRYPTION_KEY_BASE64 must decode to exactly 32 bytes');return key;}
function encryptPayload(tenant,payload){const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',encryptionKey(),iv);cipher.setAAD(Buffer.from(tenant));const ciphertext=Buffer.concat([cipher.update(JSON.stringify(payload),'utf8'),cipher.final()]);return{v:1,alg:'aes-256-gcm',iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')};}
function decryptPayload(tenant,envelope){if(!envelope||envelope.v!==1)throw new Error('unsupported encrypted payload');const decipher=crypto.createDecipheriv('aes-256-gcm',encryptionKey(),Buffer.from(envelope.iv,'base64'));decipher.setAAD(Buffer.from(tenant));decipher.setAuthTag(Buffer.from(envelope.tag,'base64'));return JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,'base64')),decipher.final()]).toString('utf8'));}
function normalizeMemory(input){const value=input||{};const content=String(value.content||'').trim();const errors=[];if(content.length<2||content.length>50000)errors.push('content must contain 2 to 50000 characters');if(!value.subject)errors.push('subject is required');if(!value.source)errors.push('source is required');if(!value.source_event_id)errors.push('source_event_id is required');if(errors.length){const error=new Error(errors.join('; '));error.status=422;throw error;}return{content,subject:String(value.subject).slice(0,255),source:String(value.source).slice(0,120),source_event_id:String(value.source_event_id).slice(0,160),namespace:String(value.namespace||'default').slice(0,120),tags:Array.isArray(value.tags)?value.tags.slice(0,50).map(String):[],metadata:value.metadata&&typeof value.metadata==='object'?value.metadata:{}};}
function contentHash(memory){return crypto.createHash('sha256').update(JSON.stringify({subject:memory.subject,content:memory.content,tags:memory.tags})).digest('hex');}
function tokens(value){return new Set(String(value||'').toLowerCase().match(/[a-z0-9]{2,}/g)||[]);}
function relevance(query,memory){const q=tokens(query),d=tokens(`${memory.subject} ${memory.content} ${(memory.tags||[]).join(' ')}`);if(!q.size)return 0;let overlap=0;for(const token of q)if(d.has(token))overlap++;return overlap/q.size;}
function rankMemories(query,memories,limit=10){return memories.map((memory)=>({...memory,relevance:relevance(query,memory)})).filter((memory)=>memory.relevance>0).sort((a,b)=>b.relevance-a.relevance||new Date(b.created_at)-new Date(a.created_at)).slice(0,Math.min(50,Math.max(1,limit)));}
function evaluationMetrics(cases){const total=cases.length;const hits=cases.filter((item)=>item.hit).length;const contamination=cases.filter((item)=>item.cross_tenant_result).length;return{total,hits,misses:total-hits,recall_at_k:total?hits/total:0,contamination_count:contamination,contamination_rate:total?contamination/total:0};}
module.exports={contentHash,decryptPayload,encryptPayload,encryptionKey,evaluationMetrics,injectionFlags,normalizeMemory,rankMemories};
